/*
 * 
 * 
 * Copyright (C) 2012 Diego Schmaedech & Laboratório de Educação Cerebral
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package looktable;

import javax.swing.JPanel;
import looktable.models.GameModel;

/**
 *
 * @author schmaedech
 */
public class ConfigurationPanel extends javax.swing.JPanel {

    MainFrame aThis;

    public ConfigurationPanel(MainFrame aThis) {
        initComponents();
        this.aThis = aThis;
       
       
        //throw new UnsupportedOperationException("Not yet implemented");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jpFront = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jsRow = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jsCol = new javax.swing.JSpinner();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jpFront3 = new javax.swing.JPanel();
        jcbShowTime = new javax.swing.JCheckBox();
        jcbShowLast = new javax.swing.JCheckBox();
        jcbRanMode = new javax.swing.JCheckBox();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jpFront4 = new javax.swing.JPanel();
        jbStartGame = new javax.swing.JButton();

        setBackground(new java.awt.Color(254, 254, 254));
        setLayout(new java.awt.GridLayout(1, 3));

        jLayeredPane1.setLayout(new java.awt.GridLayout());

        jpFront.setBackground(new java.awt.Color(153, 0, 153));
        jpFront.setOpaque(false);
        jpFront.setLayout(new java.awt.GridLayout(4, 0));

        jLabel1.setBackground(new java.awt.Color(63, 63, 70));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(63, 63, 70));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LINHAS");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jpFront.add(jLabel1);

        jsRow.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jsRow.setModel(new javax.swing.SpinnerNumberModel(2, 2, 10, 1));
        jpFront.add(jsRow);

        jLabel2.setBackground(new java.awt.Color(63, 63, 70));
        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(63, 63, 70));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("COLUNAS");
        jpFront.add(jLabel2);

        jsCol.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jsCol.setModel(new javax.swing.SpinnerNumberModel(2, 2, 10, 1));
        jpFront.add(jsCol);

        jLayeredPane1.add(jpFront);

        add(jLayeredPane1);

        jLayeredPane4.setLayout(new java.awt.BorderLayout());

        jpFront3.setBackground(new java.awt.Color(153, 0, 153));
        jpFront3.setOpaque(false);
        jpFront3.setLayout(new java.awt.GridLayout(3, 0));

        jcbShowTime.setBackground(new java.awt.Color(63, 63, 70));
        jcbShowTime.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jcbShowTime.setForeground(new java.awt.Color(63, 63, 70));
        jcbShowTime.setText("mostrar tempo");
        jcbShowTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpFront3.add(jcbShowTime);

        jcbShowLast.setBackground(new java.awt.Color(63, 63, 70));
        jcbShowLast.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jcbShowLast.setForeground(new java.awt.Color(63, 63, 70));
        jcbShowLast.setText("mostrar última");
        jcbShowLast.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpFront3.add(jcbShowLast);

        jcbRanMode.setBackground(new java.awt.Color(63, 63, 70));
        jcbRanMode.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jcbRanMode.setForeground(new java.awt.Color(63, 63, 70));
        jcbRanMode.setText("modo aleatório");
        jcbRanMode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpFront3.add(jcbRanMode);

        jLayeredPane4.add(jpFront3, java.awt.BorderLayout.CENTER);

        add(jLayeredPane4);

        jLayeredPane5.setLayout(new java.awt.GridLayout(1, 1));

        jpFront4.setBackground(new java.awt.Color(153, 0, 153));
        jpFront4.setOpaque(false);
        jpFront4.setLayout(new java.awt.GridLayout());

        jbStartGame.setBackground(new java.awt.Color(204, 204, 204));
        jbStartGame.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbStartGame.setForeground(new java.awt.Color(204, 204, 204));
        jbStartGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/glyphicons_173_play.png"))); // NOI18N
        jbStartGame.setToolTipText("");
        jbStartGame.setBorder(null);
        jbStartGame.setBorderPainted(false);
        jbStartGame.setContentAreaFilled(false);
        jbStartGame.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbStartGame.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbStartGameActionPerformed(evt);
            }
        });
        jpFront4.add(jbStartGame);

        jLayeredPane5.add(jpFront4);

        add(jLayeredPane5);
    }// </editor-fold>//GEN-END:initComponents

    private void jbStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbStartGameActionPerformed

        GameModel.jsCol = jsCol;
        GameModel.jsRow = jsCol;
        GameModel.showTime = jcbShowTime.isSelected();
        GameModel.showLastNumber = jcbShowLast.isSelected();
        GameModel.isRanMode = jcbRanMode.isSelected();
        aThis.gotoGame();
    }//GEN-LAST:event_jbStartGameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JButton jbStartGame;
    private javax.swing.JCheckBox jcbRanMode;
    private javax.swing.JCheckBox jcbShowLast;
    private javax.swing.JCheckBox jcbShowTime;
    private javax.swing.JPanel jpFront;
    private javax.swing.JPanel jpFront3;
    private javax.swing.JPanel jpFront4;
    private javax.swing.JSpinner jsCol;
    private javax.swing.JSpinner jsRow;
    // End of variables declaration//GEN-END:variables
}
